apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas:  1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      annotations:
        metrics.dynatrace.com/path: /stats/prometheus
        metrics.dynatrace.com/port: "15020"
        metrics.dynatrace.com/scrape: "true"
        metrics.dynatrace.com/secure: "false"
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: databases-secret
                  key: pgdb-user-name
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databases-secret
                  key: pgdb-user-pass
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: pg-init-path
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: pg-init-path
          hostPath:
            path: /Users/ihudak/dev/dec.21/k8s/k8s-databases/postgres/init
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  type: LoadBalancer
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 31432
