apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
  namespace: databases
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  # Retain. Set it to Delete when removing the volume to delete the files - so it triggers the docker-entrypoint
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {CURDIR}/mnt
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-claim
  namespace: databases
spec:
  volumeName: mongo-pv-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: databases
  labels:
    app: mongo
spec:
  replicas:  1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      namespace: databases
      annotations:
        metrics.dynatrace.com/path: /stats/prometheus
        metrics.dynatrace.com/port: "15020"
        metrics.dynatrace.com/scrape: "true"
        metrics.dynatrace.com/secure: "false"
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: databases-secret
                  key: mongo-user-name
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databases-secret
                  key: mongo-user-pass
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
              readOnly: false
            - name: mongo-init-path
              mountPath: /docker-entrypoint-initdb.d/
              readOnly: true
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
      volumes:
        - name: mongo-persistent-storage
#          hostPath:
#            path: {CURDIR}/mnt
#            type: Directory
          persistentVolumeClaim:
            claimName: mongo-persistent-claim
        - name: mongo-init-path
          hostPath:
            path: {CURDIR}/init
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: databases
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
#      nodePort: 31307
